/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Test_JNI */

#ifndef _Included_Test_JNI
#define _Included_Test_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Test_JNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Test_1JNI_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     Test_JNI
 * Method:    calculate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Test_1JNI_calculate
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
